server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
    password: #密码
    timeout: 30000
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/aj_smb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

#showSql
logging:
  level:
    root: info
    com:
      example:
        mapper : debug